CREATE TABLE IF NOT EXISTS cities (
    name TEXT PRIMARY KEY,
    intown BOOLEAN NOT NULL DEFAULT FALSE,
    outtown BOOLEAN NOT NULL DEFAULT FALSE,
    extended BOOLEAN NOT NULL DEFAULT FALSE
);
INSERT INTO cities (name, intown, outtown, extended) VALUES
('AMHEARST', FALSE, TRUE, FALSE),
('Aamrillo', TRUE, FALSE, FALSE),
('Abernathy', FALSE, TRUE, FALSE),
('Amaraillo', TRUE, FALSE, FALSE),
('Amariilo', TRUE, FALSE, FALSE),
('Amarill', TRUE, FALSE, FALSE),
('Amarilllo', TRUE, FALSE, FALSE),
('Amarillo', TRUE, FALSE, FALSE),
('Amarillo/Bushland', FALSE, TRUE, FALSE),
('Amarilo', TRUE, FALSE, FALSE),
('Amarllo', TRUE, FALSE, FALSE),
('Amherst', FALSE, TRUE, FALSE),
('Anton', FALSE, TRUE, FALSE),
('Bledsoe', FALSE, FALSE, TRUE),
('Borger', FALSE, TRUE, FALSE),
('Bovina', FALSE, FALSE, TRUE),
('Boys Ranch', FALSE, TRUE, FALSE),
('Brownfield', FALSE, TRUE, FALSE),
('Bushland', FALSE, TRUE, FALSE),
('Canyon', TRUE, FALSE, FALSE),
('Canyon Tx', TRUE, FALSE, FALSE),
('Clarendon', FALSE, FALSE, TRUE),
('Claude', FALSE, TRUE, FALSE),
('Clovis', FALSE, FALSE, TRUE),
('Cotton Center', FALSE, TRUE, FALSE),
('Crosby', FALSE, TRUE, FALSE),
('Crosbyton', FALSE, TRUE, FALSE),
('Dalhart', FALSE, FALSE, TRUE),
('Denver City', FALSE, FALSE, TRUE),
('Dickens', FALSE, FALSE, TRUE),
('Dimmit', FALSE, FALSE, TRUE),
('Dimmitt', FALSE, FALSE, TRUE),
('Dougherty', FALSE, FALSE, TRUE),
('Earth', FALSE, TRUE, FALSE),
('Edmonson', FALSE, FALSE, TRUE),
('FLOYADA', FALSE, TRUE, FALSE),
('Farwell', FALSE, FALSE, TRUE),
('Flomot', FALSE, FALSE, TRUE),
('Floydada', FALSE, TRUE, FALSE),
('Floydada/Flomot', FALSE, FALSE, TRUE),
('Friona', FALSE, FALSE, TRUE),
('Fritch', FALSE, TRUE, FALSE),
('Gail', FALSE, FALSE, TRUE),
('Girard', FALSE, FALSE, TRUE),
('Groom', FALSE, FALSE, TRUE),
('Hale Center', FALSE, TRUE, FALSE),
('Happy', FALSE, TRUE, FALSE),
('Hart', FALSE, FALSE, TRUE),
('Hedley', FALSE, FALSE, TRUE),
('Hereford', FALSE, FALSE, TRUE),
('Howardwick', FALSE, FALSE, TRUE),
('Idalou', FALSE, TRUE, FALSE),
('Jayton', FALSE, FALSE, TRUE),
('Justicberg', FALSE, FALSE, TRUE),
('Justiceburg', FALSE, FALSE, TRUE),
('Kress', FALSE, FALSE, TRUE),
('LBN', TRUE, FALSE, FALSE),
('Lamesa', FALSE, TRUE, FALSE),
('Lariat', FALSE, FALSE, TRUE),
('Lazbuddie', FALSE, FALSE, TRUE),
('Lbk', TRUE, FALSE, FALSE),
('Levelland', FALSE, TRUE, FALSE),
('Littlefield', FALSE, TRUE, FALSE),
('Lland', FALSE, TRUE, FALSE),
('Lockney', FALSE, FALSE, TRUE),
('Loerenzo', FALSE, TRUE, FALSE),
('Loop', FALSE, TRUE, FALSE),
('Lorenzo', FALSE, TRUE, FALSE),
('Ltf', FALSE, TRUE, FALSE),
('Lub', TRUE, FALSE, FALSE),
('Lubb', TRUE, FALSE, FALSE),
('Lubbbock', TRUE, FALSE, FALSE),
('Lubbck', TRUE, FALSE, FALSE),
('Lubbcok', TRUE, FALSE, FALSE),
('Lubbock', TRUE, FALSE, FALSE),
('Lubbock/Denver City', FALSE, FALSE, TRUE),
('Lubbock/New Deal', FALSE, TRUE, FALSE),
('Matador', FALSE, FALSE, TRUE),
('McAdoo', FALSE, FALSE, TRUE),
('Meadow', FALSE, TRUE, FALSE),
('Memphis', FALSE, FALSE, TRUE),
('Morton', FALSE, TRUE, FALSE),
('Morton/Maple', FALSE, FALSE, TRUE),
('Muleshoe', FALSE, FALSE, TRUE),
('Nazareth', FALSE, FALSE, TRUE),
('New Deal', FALSE, TRUE, FALSE),
('New Home', FALSE, TRUE, FALSE),
('O''Donell', FALSE, TRUE, FALSE),
('Odonnell', FALSE, TRUE, FALSE),
('Olton', FALSE, TRUE, FALSE),
('Pampa', FALSE, FALSE, TRUE),
('Panhandle', FALSE, TRUE, FALSE),
('Petersburg', FALSE, TRUE, FALSE),
('Plains', FALSE, FALSE, TRUE),
('Plainview', FALSE, TRUE, FALSE),
('Plv', FALSE, TRUE, FALSE),
('Portales', FALSE, FALSE, TRUE),
('Post', FALSE, TRUE, FALSE),
('Quitaque', FALSE, FALSE, TRUE),
('Ralls', FALSE, TRUE, FALSE),
('Ransom Canyon', FALSE, TRUE, FALSE),
('Roarding Springs', FALSE, FALSE, TRUE),
('Roaring Springs', FALSE, FALSE, TRUE),
('Ropesville', FALSE, TRUE, FALSE),
('SHAMROCK', FALSE, FALSE, TRUE),
('Seagraves', FALSE, TRUE, FALSE),
('Seminole', FALSE, FALSE, TRUE),
('Shallowater', FALSE, TRUE, FALSE),
('Silverton', FALSE, FALSE, TRUE),
('Skellytown', FALSE, TRUE, FALSE),
('Slaton', FALSE, TRUE, FALSE),
('Smyer', FALSE, TRUE, FALSE),
('Snyder', FALSE, FALSE, TRUE),
('Spearman', FALSE, FALSE, TRUE),
('Springlake', FALSE, TRUE, FALSE),
('Spur', FALSE, FALSE, TRUE),
('Stinnett', FALSE, TRUE, FALSE),
('Sudan', FALSE, TRUE, FALSE),
('Sundown', FALSE, TRUE, FALSE),
('Sunnyside/Hereford', FALSE, FALSE, TRUE),
('Tahoka', FALSE, TRUE, FALSE),
('Texico', FALSE, FALSE, TRUE),
('Tokio', FALSE, FALSE, TRUE),
('Tulia', FALSE, FALSE, TRUE),
('Turkey', FALSE, FALSE, TRUE),
('Valle de Oro', FALSE, TRUE, FALSE),
('Vega', FALSE, TRUE, FALSE),
('Wayside', FALSE, TRUE, FALSE),
('Welch', FALSE, TRUE, FALSE),
('Wellington', FALSE, FALSE, TRUE),
('Wellman', FALSE, TRUE, FALSE),
('White Deer', FALSE, TRUE, FALSE),
('Whiteface', FALSE, TRUE, FALSE),
('Wildorado', FALSE, TRUE, FALSE),
('Wilson', FALSE, TRUE, FALSE),
('Wofforth', FALSE, TRUE, FALSE),
('Wolfforth', FALSE, TRUE, FALSE),
('Wolffoth', FALSE, TRUE, FALSE),
('Wolforth, Tx', FALSE, TRUE, FALSE);